/* lessico dictionary — edit or grow this file (up to a few thousand entries).
   Each entry: { it, de, its, des, level, topic }
   it/de = the word (with article for nouns / infinitive for verbs)
   its/des = example sentence in that language (same idea both sides)
   level = A1..C2 · topic = any label you like (used by the Topic filter)
   After editing, use Settings -> "Merge dictionary" in the app to pull in new words
   without losing your progress, or "Reset to dictionary" to start clean. */
window.LESSICO_SEED = [
/* ---- B2 · Household ---- */
{it:"le faccende domestiche",de:"die Hausarbeit",its:"Ci dividiamo le faccende domestiche in modo che nessuno si senta sovraccarico.",des:"Wir teilen uns die Hausarbeit so auf, dass sich niemand überlastet fühlt.",level:"B2",topic:"Household"},
{it:"passare l'aspirapolvere",de:"staubsaugen",its:"Prima che arrivino gli ospiti, passo velocemente l'aspirapolvere in salotto.",des:"Bevor die Gäste kommen, sauge ich schnell im Wohnzimmer Staub.",level:"B2",topic:"Household"},
{it:"stendere il bucato",de:"die Wäsche aufhängen",its:"Se non stendo il bucato subito, i vestiti prendono un cattivo odore.",des:"Wenn ich die Wäsche nicht sofort aufhänge, riechen die Kleider unangenehm.",level:"B2",topic:"Household"},
{it:"stirare",de:"bügeln",its:"Odio stirare le camicie, perciò cerco di comprarne di stropicciabili.",des:"Ich hasse es, Hemden zu bügeln, deshalb kaufe ich möglichst knitterfreie.",level:"B2",topic:"Household"},
{it:"sparecchiare",de:"abräumen",its:"Dopo cena tocca ai bambini sparecchiare la tavola.",des:"Nach dem Essen sind die Kinder dran, den Tisch abzuräumen.",level:"B2",topic:"Household"},
{it:"spolverare",de:"Staub wischen",its:"Ogni sabato spolvero i mobili e i ripiani della libreria.",des:"Jeden Samstag wische ich Staub von den Möbeln und den Regalen.",level:"B2",topic:"Household"},
{it:"il detersivo",de:"das Waschmittel",its:"Preferisco un detersivo ecologico che non irriti la pelle dei bambini.",des:"Ich bevorzuge ein umweltfreundliches Waschmittel, das die Kinderhaut nicht reizt.",level:"B2",topic:"Household"},
{it:"la lavastoviglie",de:"die Spülmaschine",its:"Conviene accendere la lavastoviglie soltanto quando è piena.",des:"Es lohnt sich, die Spülmaschine erst dann anzustellen, wenn sie voll ist.",level:"B2",topic:"Household"},
{it:"buttare la spazzatura",de:"den Müll rausbringen",its:"Ti ricordi di buttare la spazzatura prima di andare a letto?",des:"Denkst du daran, den Müll rauszubringen, bevor du ins Bett gehst?",level:"B2",topic:"Household"},
{it:"riordinare",de:"aufräumen",its:"I bambini devono imparare a riordinare la propria stanza da soli.",des:"Die Kinder müssen lernen, ihr Zimmer selbst aufzuräumen.",level:"B2",topic:"Household"},
{it:"il disordine",de:"die Unordnung",its:"Con un neonato in casa, un po' di disordine è inevitabile.",des:"Mit einem Säugling im Haus ist ein bisschen Unordnung unvermeidlich.",level:"B2",topic:"Household"},
{it:"innaffiare le piante",de:"die Pflanzen gießen",its:"Mentre siamo in vacanza, il vicino innaffia le nostre piante.",des:"Während wir im Urlaub sind, gießt der Nachbar unsere Pflanzen.",level:"B2",topic:"Household"},
{it:"l'elettrodomestico",de:"das Haushaltsgerät",its:"Questo elettrodomestico consuma meno energia del vecchio modello.",des:"Dieses Haushaltsgerät verbraucht weniger Strom als das alte Modell.",level:"B2",topic:"Household"},
{it:"la bolletta",de:"die Rechnung",its:"In inverno le bollette del riscaldamento aumentano parecchio.",des:"Im Winter steigen die Rechnungen für die Heizung deutlich.",level:"B2",topic:"Household"},
{it:"fare la spesa",de:"einkaufen",its:"Faccio la spesa una volta a settimana per risparmiare tempo.",des:"Ich kaufe einmal pro Woche ein, um Zeit zu sparen.",level:"B2",topic:"Household"},
{it:"la ripartizione dei compiti",de:"die Aufgabenverteilung",its:"Una ripartizione equa dei compiti evita molte discussioni in famiglia.",des:"Eine faire Aufgabenverteilung erspart der Familie viele Diskussionen.",level:"B2",topic:"Household"},
{it:"la routine quotidiana",de:"der Alltag",its:"Con due figli piccoli, la routine quotidiana richiede molta organizzazione.",des:"Mit zwei kleinen Kindern erfordert der Alltag viel Organisation.",level:"B2",topic:"Household"},
{it:"il carico mentale",de:"die mentale Belastung",its:"Spesso il carico mentale della gestione familiare ricade su un solo genitore.",des:"Oft lastet die mentale Belastung der Familienorganisation auf nur einem Elternteil.",level:"B2",topic:"Household"},
{it:"impegnativo",de:"anstrengend",its:"Occuparsi contemporaneamente della casa e dei bambini è davvero impegnativo.",des:"Sich gleichzeitig um Haushalt und Kinder zu kümmern, ist wirklich anstrengend.",level:"B2",topic:"Household"},
/* ---- B2 · Children ---- */
{it:"conciliare famiglia e lavoro",de:"Familie und Beruf vereinbaren",its:"Non è sempre facile conciliare famiglia e lavoro.",des:"Es ist nicht immer leicht, Familie und Beruf zu vereinbaren.",level:"B2",topic:"Children"},
{it:"l'educazione",de:"die Erziehung",its:"Sull'educazione dei figli i due genitori dovrebbero essere d'accordo.",des:"Bei der Erziehung der Kinder sollten sich beide Eltern einig sein.",level:"B2",topic:"Children"},
{it:"crescere",de:"großziehen",its:"Crescere un figlio da soli richiede molta forza.",des:"Ein Kind allein großzuziehen erfordert viel Kraft.",level:"B2",topic:"Children"},
{it:"il congedo parentale",de:"die Elternzeit",its:"Dopo la nascita, ha preso sei mesi di congedo parentale.",des:"Nach der Geburt hat er sechs Monate Elternzeit genommen.",level:"B2",topic:"Children"},
{it:"il pannolino",de:"die Windel",its:"Bisogna cambiare il pannolino non appena il bambino è bagnato.",des:"Man muss die Windel wechseln, sobald das Baby nass ist.",level:"B2",topic:"Children"},
{it:"il passeggino",de:"der Kinderwagen",its:"Il passeggino nuovo entra a malapena nell'ascensore.",des:"Der neue Kinderwagen passt kaum in den Aufzug.",level:"B2",topic:"Children"},
{it:"il ciuccio",de:"der Schnuller",its:"A due anni sarebbe ora di togliergli il ciuccio.",des:"Mit zwei Jahren wäre es Zeit, ihm den Schnuller abzugewöhnen.",level:"B2",topic:"Children"},
{it:"l'asilo nido",de:"die Kita",its:"Nostro figlio frequenta l'asilo nido tre giorni a settimana.",des:"Unser Sohn geht drei Tage pro Woche in die Kita.",level:"B2",topic:"Children"},
{it:"il capriccio",de:"der Wutanfall",its:"Al supermercato ha fatto un capriccio perché voleva le caramelle.",des:"Im Supermarkt bekam er einen Wutanfall, weil er Süßigkeiten wollte.",level:"B2",topic:"Children"},
{it:"viziare",de:"verwöhnen",its:"I nonni tendono a viziare i nipoti con troppi regali.",des:"Die Großeltern neigen dazu, die Enkel mit zu vielen Geschenken zu verwöhnen.",level:"B2",topic:"Children"},
{it:"il pisolino",de:"der Mittagsschlaf",its:"Dopo il pisolino pomeridiano il bambino è molto più tranquillo.",des:"Nach dem Mittagsschlaf ist das Kind viel ausgeglichener.",level:"B2",topic:"Children"},
{it:"addormentarsi",de:"einschlafen",its:"Il piccolo fatica ad addormentarsi senza la sua coperta.",des:"Der Kleine kann ohne seine Decke nur schwer einschlafen.",level:"B2",topic:"Children"},
{it:"i compiti",de:"die Hausaufgaben",its:"Dopo la scuola deve finire i compiti prima di giocare.",des:"Nach der Schule muss er die Hausaufgaben fertig machen, bevor er spielt.",level:"B2",topic:"Children"},
{it:"sorvegliare",de:"beaufsichtigen",its:"Bisogna sempre sorvegliare i bambini quando giocano vicino all'acqua.",des:"Man sollte Kinder immer beaufsichtigen, wenn sie am Wasser spielen.",level:"B2",topic:"Children"},
{it:"i fratelli",de:"die Geschwister",its:"I fratelli litigano spesso, ma in fondo si vogliono bene.",des:"Die Geschwister streiten sich oft, aber im Grunde haben sie sich lieb.",level:"B2",topic:"Children"},
{it:"la gelosia",de:"die Eifersucht",its:"Dopo la nascita del secondo figlio, un po' di gelosia è normale.",des:"Nach der Geburt des zweiten Kindes ist ein wenig Eifersucht ganz normal.",level:"B2",topic:"Children"},
{it:"rimproverare",de:"schimpfen",its:"Invece di rimproverarlo subito, cerco di spiegargli l'errore.",des:"Anstatt sofort mit ihm zu schimpfen, versuche ich, ihm den Fehler zu erklären.",level:"B2",topic:"Children"},
{it:"la ricompensa",de:"die Belohnung",its:"Come ricompensa per i buoni voti, andremo al cinema.",des:"Als Belohnung für die guten Noten gehen wir ins Kino.",level:"B2",topic:"Children"},
{it:"obbediente",de:"gehorsam",its:"Non pretendo un figlio sempre obbediente, ma rispettoso sì.",des:"Ich erwarte kein immer gehorsames Kind, aber ein respektvolles schon.",level:"B2",topic:"Children"},
{it:"testardo",de:"stur",its:"È così testardo che non cambia idea nemmeno davanti ai fatti.",des:"Er ist so stur, dass er selbst angesichts der Fakten seine Meinung nicht ändert.",level:"B2",topic:"Children"},
{it:"sfinito",de:"erschöpft",its:"La sera, dopo aver messo a letto i bambini, siamo completamente sfiniti.",des:"Abends, nachdem wir die Kinder ins Bett gebracht haben, sind wir völlig erschöpft.",level:"B2",topic:"Children"},
{it:"la pazienza",de:"die Geduld",its:"Educare i figli richiede molta pazienza e coerenza.",des:"Kinder zu erziehen erfordert viel Geduld und Konsequenz.",level:"B2",topic:"Children"},
{it:"la responsabilità",de:"die Verantwortung",its:"Prendersi cura di un neonato è una grande responsabilità.",des:"Sich um einen Säugling zu kümmern, ist eine große Verantwortung.",level:"B2",topic:"Children"},
{it:"allattare",de:"stillen",its:"Ha deciso di allattare il bambino per i primi sei mesi.",des:"Sie hat beschlossen, das Baby die ersten sechs Monate zu stillen.",level:"B2",topic:"Children"},
{it:"il pediatra",de:"der Kinderarzt",its:"Portiamo la bambina dal pediatra per i controlli di routine.",des:"Wir bringen die Kleine für die Routineuntersuchungen zum Kinderarzt.",level:"B2",topic:"Children"},
{it:"coccolare",de:"kuscheln",its:"La sera ci piace coccolare i bambini leggendo una favola.",des:"Abends kuscheln wir gern mit den Kindern und lesen ein Märchen.",level:"B2",topic:"Children"},
{it:"il lettino",de:"das Kinderbett",its:"Abbiamo spostato il lettino accanto al nostro letto.",des:"Wir haben das Kinderbett neben unser Bett gestellt.",level:"B2",topic:"Children"},
{it:"brontolare",de:"meckern",its:"Smette di brontolare solo quando ottiene ciò che vuole.",des:"Er hört erst auf zu meckern, wenn er bekommt, was er will.",level:"B2",topic:"Children"},
{it:"affidare",de:"anvertrauen",its:"La sera affidiamo i bambini a una babysitter di fiducia.",des:"Abends vertrauen wir die Kinder einem zuverlässigen Babysitter an.",level:"B2",topic:"Children"},
{it:"le regole",de:"die Regeln",its:"In casa nostra le regole valgono per tutti, anche per gli adulti.",des:"Bei uns zu Hause gelten die Regeln für alle, auch für die Erwachsenen.",level:"B2",topic:"Children"},
{it:"lo sviluppo",de:"die Entwicklung",its:"Ogni bambino ha i suoi tempi di sviluppo e non serve fare paragoni.",des:"Jedes Kind hat sein eigenes Tempo in der Entwicklung, und Vergleiche bringen nichts.",level:"B2",topic:"Children"},
/* ---- B1 · Household ---- */
{it:"la cucina",de:"die Küche",its:"In cucina c'è sempre un buon odore quando la mamma cucina.",des:"In der Küche riecht es immer gut, wenn Mama kocht.",level:"B1",topic:"Household"},
{it:"cucinare",de:"kochen",its:"Il fine settimana mi piace cucinare qualcosa di speciale.",des:"Am Wochenende koche ich gern etwas Besonderes.",level:"B1",topic:"Household"},
{it:"lavare i piatti",de:"abwaschen",its:"Chi cucina non lava i piatti, questa è la regola.",des:"Wer kocht, wäscht nicht ab, das ist die Regel.",level:"B1",topic:"Household"},
{it:"la camera da letto",de:"das Schlafzimmer",its:"La nostra camera da letto è piccola ma accogliente.",des:"Unser Schlafzimmer ist klein, aber gemütlich.",level:"B1",topic:"Household"},
{it:"il salotto",de:"das Wohnzimmer",its:"La sera guardiamo la televisione in salotto.",des:"Abends schauen wir im Wohnzimmer fern.",level:"B1",topic:"Household"},
{it:"il bagno",de:"das Badezimmer",its:"Il bagno è occupato, puoi aspettare cinque minuti?",des:"Das Badezimmer ist besetzt, kannst du fünf Minuten warten?",level:"B1",topic:"Household"},
{it:"pulire",de:"putzen",its:"Il sabato mattina puliamo tutta la casa insieme.",des:"Am Samstagmorgen putzen wir zusammen die ganze Wohnung.",level:"B1",topic:"Household"},
{it:"la scopa",de:"der Besen",its:"Prendi la scopa, per favore, ci sono delle briciole sul pavimento.",des:"Hol bitte den Besen, auf dem Boden liegen Krümel.",level:"B1",topic:"Household"},
{it:"spazzare",de:"fegen",its:"Dopo cena spazzo sempre il pavimento della cucina.",des:"Nach dem Essen fege ich immer den Küchenboden.",level:"B1",topic:"Household"},
{it:"la finestra",de:"das Fenster",its:"Apri la finestra, fa caldo qui dentro.",des:"Mach das Fenster auf, hier drinnen ist es warm.",level:"B1",topic:"Household"},
{it:"la porta",de:"die Tür",its:"Chiudi la porta, per favore, entra freddo.",des:"Mach bitte die Tür zu, es zieht.",level:"B1",topic:"Household"},
{it:"il frigorifero",de:"der Kühlschrank",its:"Il latte è nel frigorifero, in alto a destra.",des:"Die Milch ist im Kühlschrank, oben rechts.",level:"B1",topic:"Household"},
{it:"il forno",de:"der Backofen",its:"Metto la pizza nel forno per dieci minuti.",des:"Ich schiebe die Pizza für zehn Minuten in den Backofen.",level:"B1",topic:"Household"},
{it:"la lavatrice",de:"die Waschmaschine",its:"La lavatrice ha finito, possiamo stendere i panni.",des:"Die Waschmaschine ist fertig, wir können die Wäsche aufhängen.",level:"B1",topic:"Household"},
{it:"il letto",de:"das Bett",its:"I bambini vanno a letto alle otto di sera.",des:"Die Kinder gehen um acht Uhr abends ins Bett.",level:"B1",topic:"Household"},
{it:"fare il letto",de:"das Bett machen",its:"Ogni mattina i bambini devono fare il letto.",des:"Jeden Morgen müssen die Kinder ihr Bett machen.",level:"B1",topic:"Household"},
{it:"la sedia",de:"der Stuhl",its:"Manca una sedia a tavola per il nostro ospite.",des:"Am Tisch fehlt ein Stuhl für unseren Gast.",level:"B1",topic:"Household"},
{it:"il tavolo",de:"der Tisch",its:"Mettiamo il regalo sul tavolo della cucina.",des:"Wir legen das Geschenk auf den Küchentisch.",level:"B1",topic:"Household"},
{it:"l'armadio",de:"der Schrank",its:"I vestiti puliti sono già nell'armadio.",des:"Die sauberen Kleider sind schon im Schrank.",level:"B1",topic:"Household"},
{it:"il cassetto",de:"die Schublade",its:"Le posate sono nel primo cassetto a sinistra.",des:"Das Besteck ist in der ersten Schublade links.",level:"B1",topic:"Household"},
{it:"apparecchiare la tavola",de:"den Tisch decken",its:"Puoi apparecchiare la tavola mentre finisco di cucinare?",des:"Kannst du den Tisch decken, während ich zu Ende koche?",level:"B1",topic:"Household"},
{it:"la spugna",de:"der Schwamm",its:"Pulisci il tavolo con la spugna, per favore.",des:"Wisch bitte den Tisch mit dem Schwamm ab.",level:"B1",topic:"Household"},
{it:"asciugare",de:"abtrocknen",its:"Tu lavi e io asciugo i piatti, va bene?",des:"Du wäschst ab und ich trockne das Geschirr ab, einverstanden?",level:"B1",topic:"Household"},
{it:"la chiave",de:"der Schlüssel",its:"La chiave di casa è appesa vicino alla porta.",des:"Der Schlüssel hängt neben der Tür.",level:"B1",topic:"Household"},
{it:"accendere la luce",de:"das Licht anmachen",its:"È buio, accendi la luce per favore.",des:"Es ist dunkel, mach bitte das Licht an.",level:"B1",topic:"Household"},
/* ---- B1 · Children ---- */
{it:"il bambino",de:"das Kind",its:"Il bambino gioca in giardino con il cane.",des:"Das Kind spielt im Garten mit dem Hund.",level:"B1",topic:"Children"},
{it:"giocare",de:"spielen",its:"I bambini giocano insieme al parco ogni pomeriggio.",des:"Die Kinder spielen jeden Nachmittag zusammen im Park.",level:"B1",topic:"Children"},
{it:"il giocattolo",de:"das Spielzeug",its:"Dopo aver giocato, rimetti i giocattoli nella scatola.",des:"Nach dem Spielen räumst du das Spielzeug in die Kiste.",level:"B1",topic:"Children"},
{it:"dormire",de:"schlafen",its:"Il neonato dorme quasi tutto il giorno.",des:"Das Baby schläft fast den ganzen Tag.",level:"B1",topic:"Children"},
{it:"svegliarsi",de:"aufwachen",its:"La bambina si sveglia spesso durante la notte.",des:"Das Mädchen wacht nachts oft auf.",level:"B1",topic:"Children"},
{it:"piangere",de:"weinen",its:"Il piccolo piange perché ha fame.",des:"Der Kleine weint, weil er Hunger hat.",level:"B1",topic:"Children"},
{it:"ridere",de:"lachen",its:"Quando il papà fa le facce buffe, i bambini ridono.",des:"Wenn Papa Grimassen macht, lachen die Kinder.",level:"B1",topic:"Children"},
{it:"mangiare",de:"essen",its:"A pranzo i bambini mangiano pasta e verdura.",des:"Zu Mittag essen die Kinder Nudeln und Gemüse.",level:"B1",topic:"Children"},
{it:"la merenda",de:"der Snack",its:"Nel pomeriggio prepariamo una merenda con frutta e pane.",des:"Am Nachmittag machen wir einen Snack mit Obst und Brot.",level:"B1",topic:"Children"},
{it:"il biberon",de:"das Fläschchen",its:"La mamma prepara il biberon per il neonato.",des:"Die Mama macht das Fläschchen für das Baby fertig.",level:"B1",topic:"Children"},
{it:"imparare",de:"lernen",its:"A scuola i bambini imparano a leggere e a scrivere.",des:"In der Schule lernen die Kinder lesen und schreiben.",level:"B1",topic:"Children"},
{it:"disegnare",de:"malen",its:"Mia figlia ama disegnare animali con i pennarelli.",des:"Meine Tochter malt gern Tiere mit Filzstiften.",level:"B1",topic:"Children"},
{it:"il disegno",de:"die Zeichnung",its:"Ha appeso il suo disegno sul frigorifero.",des:"Sie hat ihre Zeichnung an den Kühlschrank gehängt.",level:"B1",topic:"Children"},
{it:"raccontare una storia",de:"eine Geschichte erzählen",its:"Ogni sera papà racconta una storia prima di dormire.",des:"Jeden Abend erzählt Papa vor dem Schlafen eine Geschichte.",level:"B1",topic:"Children"},
{it:"abbracciare",de:"umarmen",its:"La bambina abbraccia forte la sua mamma.",des:"Das Mädchen umarmt seine Mama fest.",level:"B1",topic:"Children"},
{it:"la scuola",de:"die Schule",its:"Mio figlio va a scuola a piedi ogni mattina.",des:"Mein Sohn geht jeden Morgen zu Fuß zur Schule.",level:"B1",topic:"Children"},
{it:"la maestra",de:"die Lehrerin",its:"La maestra è molto gentile con i bambini.",des:"Die Lehrerin ist sehr nett zu den Kindern.",level:"B1",topic:"Children"},
{it:"i genitori",de:"die Eltern",its:"I genitori aspettano i bambini davanti alla scuola.",des:"Die Eltern warten vor der Schule auf die Kinder.",level:"B1",topic:"Children"},
{it:"la nonna",de:"die Oma",its:"La nonna prepara sempre una buona torta la domenica.",des:"Die Oma backt sonntags immer einen guten Kuchen.",level:"B1",topic:"Children"},
{it:"il nonno",de:"der Opa",its:"Il nonno porta i bambini a giocare al parco.",des:"Der Opa nimmt die Kinder zum Spielen in den Park mit.",level:"B1",topic:"Children"},
{it:"il compleanno",de:"der Geburtstag",its:"Domani è il compleanno di mia figlia e facciamo una festa.",des:"Morgen hat meine Tochter Geburtstag und wir feiern.",level:"B1",topic:"Children"},
{it:"il regalo",de:"das Geschenk",its:"Il bambino apre il regalo con grande gioia.",des:"Das Kind packt das Geschenk voller Freude aus.",level:"B1",topic:"Children"},
{it:"avere paura",de:"Angst haben",its:"Di notte il piccolo ha paura del buio.",des:"Nachts hat der Kleine Angst vor der Dunkelheit.",level:"B1",topic:"Children"},
{it:"lavarsi i denti",de:"die Zähne putzen",its:"Prima di dormire i bambini si lavano i denti.",des:"Vor dem Schlafen putzen sich die Kinder die Zähne.",level:"B1",topic:"Children"},
{it:"vestirsi",de:"sich anziehen",its:"Al mattino mia figlia si veste da sola.",des:"Am Morgen zieht sich meine Tochter allein an.",level:"B1",topic:"Children"}
];
